name: default
windows:
  - default:
      layout: 69ec,211x58,0,0{130x58,0,0,3,80x58,131,0[80x29,131,0,7,80x28,131,30,8]
      panes:
        - 
        - 
        - btop
  - remote:
      layout: cd61,211x58,0,0,4
      panes:
        -
